#!/bin/bash

# Asegurarse de que se proporcione un parámetro
if [ -z "$1" ]; then
    echo "Error: No se ha proporcionado un parámetro."
    echo "Uso: cpc use <nombre>"
    exit
fi

# Aquí puedes agregar la lógica que deseas ejecutar con el comando 'use'
echo "Ejecutando comando 'use' con el parámetro: $1"